### ISSUE TITLE
http.Client timeout.

### ISSUE THREAD

**Issue by sarg** [mvdan/fdroidcl#36]
Please set reasonable timeout for http.Client. As for now fdroidcl may show `Downloading update...` without displaying any progress.

**Comment by mvdan** [comment]
The default timeouts apply; see https://golang.org/pkg/net/http/#RoundTripper. For example, dialing stops after 30s, and the TLS handshake has 10s. There's no timeout on downloading the request body; otherwise, downloading a very large APK over a slow connection could error.

I agree that not reporting progress isn't ideal, but this is not an interactive tool. I think the underlying issue here is that f-droid.org can be very slow at times.

**Comment by sarg** [comment]
Okay then. I'll set global timeout in my script, given that I know how long update usually takes.
I agree that main use for fdroidcl is in non-interactive scenarios. But if you'll implement simple progress display like wget does it'll be nice.

```
 70%[=======================>                    ] 615.76K   886KB/s
```

**Comment by Apfelwurm** [comment]
@sarg how did you set the global timeout? I've searched many times now and didn't find anything that would not involve code changes

**Comment by sarg** [comment]
@Apfelwurm I've meant something like https://www.man7.org/linux/man-pages/man1/timeout.1.html

**Comment by Apfelwurm** [comment]
well, some things can be so simple :'D Thank you very much!
