### ISSUE TITLE
Allow install & uninstall for a specific user

### ISSUE THREAD

**Issue by ropery** [mvdan/fdroidcl#37]
Right now `fdroidcl` always installs apps for all users.
I request an option to basically `adb install --user <USER_ID|current|all> <pkgname>`.
Same for `uninstall`.
Thank you!

**Comment by mvdan** [comment]
Sounds fair - if you'd like to work on a patch, I'll be happy to review.

**Comment by lolilolicon** [comment]
This might not as simple as I initially thought...
First, `device.Installed()` must be modified to be able to list apps installed only for a specific user. I don't know how to do this with `dumpsys` but there is `pm list packages --user`. I wonder why `dumpsys` was chosen to begin with?
Second, `fdroidcl search -u` should also consider `--user`...

Which makes me think, perhaps we can find a simpler way to do this.
Perhaps `fdroidcl` will pass `--user current` to `adb` whenever applicable; the user merely needs to switch to another user on the phone to do business as that user.
However, we also want to be able to do it to all users; so a global `-a` will make `fdroidcl` pass `--user all` to `adb` instead.
What do you think?

**Comment by mvdan** [comment]
I believe I chose `dumpsys` instead of `pm list packages` because it printed less text and was faster. If it doesn't have this feature we need, then we shouldn't use it.

Defaulting to the current user, and adding an `-a` flag to some commands to mean "all users", seems like a fine change to me. If anyone ever needs this feature to be more powerful, we could always make the default configurable via the config file, so one could programmatically select a different user by modifying the JSON config.

Adding a global `-u` flag, like `fdroidcl -u=some-user install ...` seems fine too. I only worry that this could be a bit confusing for some commands - imagine `fdroidcl -u=some-user update`, which doesn't make much sense. Should that command error, or ignore the flag?

In general, we've used the config file for global settings, so I'd slightly prefer that over a flag before specifying a command. I also don't think multi-user devices are that common, as noone had brought this up yet.

Finally, `fdroidcl list users` makes sense :)

**Comment by lolilolicon** [comment]
> I believe I chose `dumpsys` instead of `pm list packages` because it printed less text and was faster. If it doesn't have this feature we need, then we shouldn't use it.
Actually, `dumpsys` provides `VersCode` and `VersName`, yet `pm` doesn't _seem_ to provide such information.
I think the way to go is simply to get a package list for a given user using `pm list packages --user`, and then use it to filter the package list we already have from `dumpsys`.

> imagine `fdroidcl -u=some-user update`, which doesn't make much sense. Should that command error, or ignore the flag?

It's OK to ignore it, since no harm is done.
Perhaps issue a gentle warning (but it should be able to pipe down given a `-q` global option.)

On the point of editing config file vs a global flag, I think a flag is better, as it's much more convenient. Unlike repo settings, which are relatively permanent, choosing a specific user is an operation that should be more agile & flexible. The default behavior I believe should be equal to `-u current`, yes.

**Comment by mvdan** [comment]
Hmm, having to call two commands would probably slow down the tool quite a lot. We'd need to investigate if there's a better way.

You've convinced me about the global flag. Though I'd prefer not to emit any warnings, to make it easier for someone to set up global flags via an alias, not having to worry about warnings.

**Comment by lolilolicon** [comment]
> having to call two commands would probably slow down the tool quite a lot.
I'd wager the majority of the time spend is in connecting to the phone, so we can call `adb shell` just once, but give it two commands in one go, eg try this:

    printf '%s\n' 'dumpsys package packages' 'pm list packages --user 10' | adb shell | less

**Comment by mvdan** [comment]
I'm not sure; we'd have to investigate.

Also, is it possible for two users to install different versions of the same app? If that were possible, that would complicate our job substantially.

Do you intend to work on this yourself, by the way?

**Comment by lolilolicon** [comment]
I have just tested. Fortunately, no, only one version of a given app is allowed. Updating an app for one user will update the app for other users who have it installed as well.

Implementing this myself is, sadly, not in my power.
Feel free to work on it only when you want & have time to. I will assist with testing.
I will also update the zsh completion, once this is implemented.

**Comment by Linus789** [comment]
Implemented with [v0.7.0](https://github.com/mvdan/fdroidcl/releases/tag/v0.7.0).
