### ISSUE TITLE
allow to reinstall app signed with different key

### ISSUE THREAD

**Issue by axet** [mvdan/fdroidcl#65]
Hello!

Reinstalling app already installed with debug and release keys can be done using:

adb uninstall -k app_id
adb intall app_id

fdroidcl currently fail to install apk if it is already installed from different source. It should check key, uninstall and install it then.

```
Downloading https://f-droid.org/repo/com.github.axet.audiorecorder_371.apk... not modified
Installing com.github.axet.audiorecorder
install: could not install com.github.axet.audiorecorder: exit status 1
```

EDIT: fdroidcl also failed to update those apps with the same error:

```
fdcroidcl install -u
```

**Comment by Linus789** [comment]
Only doing `adb uninstall -k app_id` did not work for me. I had to fully uninstall the app (`adb uninstall app_id`) in order to install it.

**Comment by axet** [comment]
You can check 'man adb' its saying:

```
adb uninstall [-k] package
         Remove this app package from the device.  -k means keep the data and cache directories.
```

But I guess this is outdated and no longer valid.

**Comment by Linus789** [comment]
Yes, what the man page states is correct. But I guess because the data and cache directories are kept, Android won’t allow installing the app with a different key. In short: uninstalling with `-k` works, but installing the app with a different key afterwards not. Well, at least that was the case for me.
